version: '3.8'
services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

